version: '3.4'

services:
  reverseproxy:
    image: reverseproxy
    build:
      context: reverse-proxy
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080
