version: '3.4'

services:
  reverseproxy:
    image: reverseproxy
    build:
      context: reverse-proxy
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 8080:8080
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
